[workspace]
members = [
    "k210-console",
    "mandelbrot",
    "game-of-life",
    "accelerometer",
    "uart-passthrough",
    "rgbcontrol",
    "weather",
    "dvp-ov",
    "glyph-mapping",
    "term-server",
    "secp256k1-test",
]

[patch.crates-io]
riscv-rt = { git = "https://github.com/laanwj/riscv-rt.git", rev = "235390d95cc03fd7db6d58f426e1d53de7c136c9" }
k210-hal = { git = "https://github.com/riscv-rust/k210-hal.git", rev = "b83e843c19a2f0bc4eb7f56322ae844818709298" }

cc = { git = "https://github.com/alexcrichton/cc-rs.git", rev = "f6f6c819b987bc3a1e9ff9778d87724de55ae8b0" }
secp256k1 = { git = "https://github.com/laanwj/rust-secp256k1.git", rev = "af6a2db2800d6569bfe2af5236b5d17b6575ab24" }
