[workspace]
members = [
    "k210-console",
    "mandelbrot",
    "game-of-life",
    "accelerometer",
    "uart-passthrough",
    "rgbcontrol",
    "weather",
    "dvp-ov",
    "glyph-mapping",
    "term-server",
]

[patch.crates-io]
riscv-rt = { git = "https://github.com/rust-embedded/riscv-rt.git", rev = "c79ec482b044c37b9f823cf1451aee73c197d380"}
k210-hal = { git = "https://github.com/riscv-rust/k210-hal.git", rev = "b83e843c19a2f0bc4eb7f56322ae844818709298" }
